import { Box, Container, Flex, Heading } from "@chakra-ui/react";
import Head from "next/head";
import { Header } from "../components";
import openGraphImageCover from "../public/open-graph-cover.png";
import { Shadow } from "../types";
import { base64, buildShadow } from "../utils";
import Link from "next/link";

const openGraphImageCoverUrl = `${process.env.NEXT_PUBLIC_DOMAIN}${openGraphImageCover.src}`;

const examples = [
  {
    id: 1,
    shadow:
      "W3siaWQiOiJkY2MxY2Q1NS02YzQ0LTRmMDQtYjM5ZC01ZDg1MjdiOTc1ZmQiLCJ4IjowLCJ5IjoxOCwiYmx1ciI6NDMsInNwcmVhZCI6NCwiaW5zZXQiOmZhbHNlLCJhY3RpdmUiOnRydWUsImNvbG9yIjoiIzAwMDAwMDFhIn0seyJpZCI6ImRmMjdjOTEyLTI2MjUtNDYyNS1hMTQ4LWFiMGZkYjE4OTQ4OCIsIngiOjAsInkiOjEwLCJibHVyIjozMiwic3ByZWFkIjowLCJpbnNldCI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiY29sb3IiOiIjMDAwMDAwMWEifV0=",
  },
];

function ExampleCard({ shadow }: { shadow: string }) {
  const shadowParsed = JSON.parse(base64.decode(shadow)) as Shadow[];

  const shadowString = shadowParsed
    .filter((i: Shadow) => i.active)
    .map(buildShadow)
    .join(",");

  return (
    <Box
      rounded={"lg"}
      h="40"
      bg={"white"}
      w="40"
      sx={{
        boxShadow: shadowString,
      }}
    />
  );
}

export default function ExamplesPage() {
  return (
    <Flex minH="100vh" w="full" direction="column">
      <Head>
        <title>Examples - Supa Shadows Generator</title>
        <meta
          name="description"
          content="Box shadows examples generated by Supa Shadows."
        />
        <meta property="og:title" content="Examples - Supa Shadows Generator" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://supa-shadows.vercel.app/" />
        <meta property="og:image" content={openGraphImageCoverUrl} />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:alt" content="Supa Shadows cover" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="supa-shadows.vercel.app" />
        <meta
          property="twitter:url"
          content="https://supa-shadows.vercel.app/"
        />
        <meta
          name="twitter:title"
          content="Examples - Supa Shadows Generator"
        />
        <meta
          name="twitter:description"
          content="Box shadows examples generated by Supa Shadows"
        />
        <meta name="twitter:image" content={openGraphImageCoverUrl} />

        <meta
          name="google-site-verification"
          content="aEdmSv4Liad52ujAs70aLu_5IVpNmPWCcRTuAj34SjQ"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="full" direction="column">
        <Header />

        <Container>
          <Flex minH="calc(100vh - 64px)" flexDirection={"column"} gap={4}>
            <Heading>Coming soon</Heading>

            <Flex gap={"4"}>
              {examples.map((e) => (
                <Link
                  key={e.id}
                  href={{
                    pathname: "/",
                    query: {
                      shadow: e.shadow,
                      utm_source: "examples",
                    },
                  }}
                >
                  <ExampleCard shadow={e.shadow} />
                </Link>
              ))}
            </Flex>
          </Flex>
        </Container>
      </Flex>
    </Flex>
  );
}
