import { Button, Container, Flex, Heading } from "@chakra-ui/react";
import openGraphImageCover from "../public/open-graph-cover.png";
import Head from "next/head";
import { Header } from "../components";
import Link from "next/link";

const openGraphImageCoverUrl = `${process.env.NEXT_PUBLIC_DOMAIN}${openGraphImageCover.src}`;

export default function ExamplesPage() {
  return (
    <Flex minH="100vh" w="full" direction="column">
      <Head>
        <title>Examples - Supa Shadows Generator</title>
        <meta
          name="description"
          content="Box shadows examples generated by Supa Shadows."
        />
        <meta property="og:title" content="Examples - Supa Shadows Generator" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://supa-shadows.vercel.app/" />
        <meta property="og:image" content={openGraphImageCoverUrl} />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:alt" content="Supa Shadows cover" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="supa-shadows.vercel.app" />
        <meta
          property="twitter:url"
          content="https://supa-shadows.vercel.app/"
        />
        <meta
          name="twitter:title"
          content="Examples - Supa Shadows Generator"
        />
        <meta
          name="twitter:description"
          content="Box shadows examples generated by Supa Shadows"
        />
        <meta name="twitter:image" content={openGraphImageCoverUrl} />

        <meta
          name="google-site-verification"
          content="aEdmSv4Liad52ujAs70aLu_5IVpNmPWCcRTuAj34SjQ"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="full" direction="column">
        <Header />

        <Container>
          <Flex minH="calc(100vh - 64px)" flexDirection={"column"} gap={4}>
            <Heading>Coming soon</Heading>
            <Button
              as={Link}
              href={{
                pathname: "/",
                search:
                  "shadow=W3siaWQiOiIwMjVlNjNkNi04Y2FlLTRiZDQtOTliYy1hYmNiMzU4MTlkOWQiLCJ4IjowLCJ5IjoxMCwiYmx1ciI6OCwic3ByZWFkIjowLCJpbnNldCI6ZmFsc2UsImFjdGl2ZSI6dHJ1ZSwiY29sb3IiOiIjMDAwMDAwMWEifSx7ImlkIjoiNTU1OWY5NDQtNjRkNy00MmNjLTk5YTEtN2Y3ODJjMGJlZTgxIiwieCI6MCwieSI6MTAsImJsdXIiOjgsInNwcmVhZCI6MCwiaW5zZXQiOmZhbHNlLCJhY3RpdmUiOnRydWUsImNvbG9yIjoiIzAwMDAwMDFhIn0seyJpZCI6IjBmNTY3MTM3LWE3NjctNGY4Yi1hNTM5LWNiZDgwMzRlMTg2OSIsIngiOjAsInkiOjEwLCJibHVyIjo4LCJzcHJlYWQiOjAsImluc2V0IjpmYWxzZSwiYWN0aXZlIjp0cnVlLCJjb2xvciI6IiMwMDAwMDAxYSJ9XQ==",
              }}
            >
              Check this example demo
            </Button>
          </Flex>
        </Container>
      </Flex>
    </Flex>
  );
}
